### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by murohi-siyabako** [murohi-siyabako/furima-32110#19]
自身のフリマアプリのURL：https://furima-32110.herokuapp.com/
Basic認証のIDとパスワード：admi 2222
出品者用のメールアドレスとパスワード：13e1076@ngu.ac.jp　hk12081927
購入者用のメールアドレスとパスワード：13e1076hk@ngu.ac.jp　kh19271208
購入用カードの番号・期限・セキュリティコード：番号4242424242424242 期限

**Comment by MasaakiTanabashi** [comment]
小林さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

挙動に問題はありませんでしたが、Issuesの記述にミスがあるようなので
そちら確認、修正をお願いします。

- Basic認証のID名：誤）admi　→　正）admin
- 購入者用のアドレスとパスワードでログインが行なえませんでした。
- クレジットカードの期限、セキュリティコードが記述されていません。（今回は、期限を3月23年、セキュリティコードが123で挙動確認を行い、実行できました）


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
